### PR TITLE
Modified glowing home page

### PR DESCRIPTION
**Pull request by Arshdeep-13**
I have updated your home page to UX design glowing home page. If you like then merge it and make sure that you follow me.
Thanks
@Arshdeep-13

### CODE REVIEW

**Comment by Rishit30G** [comment]
Hey! 
If you send me the deployed version for the same it would be awesome

**Comment by Arshdeep-13** [comment]
Should I deploy it to my side and then send url it to you?

**Comment by Arshdeep-13** [comment]
Hi @Rishit30G, 
Deployed Version :- https://rishit-profile.netlify.app/

**Comment by Rishit30G** [comment]
Hey! 

Thank you for putting in your efforts, but somehow the website is not looking pleasing with the extra glow and moreover it is lagging on scrolling 
Maybe you can try out some other feature

**Pull request closed without merging**
