### PR TITLE
Changes to Navbar

### PR DESCRIPTION
**Pull request by areeburrub**
I have changed the padding and added drop shadow which gives it a effect

### CODE REVIEW

**Comment by Rishit30G** [comment]
Hey @areeburrub !
Please add (.mp4) of the changes you have made

**Comment by areeburrub** [comment]
https://user-images.githubusercontent.com/24785527/136704105-b5b79d46-b24b-4e73-a543-952257902014.mp4
Github page sample : https://areeburrub.github.io/Personal-Portfolio/

**Comment by Rishit30G** [comment]
Check out this PR: https://github.com/Rishit30G/Personal-Portfolio/pull/16
This might help!

**Comment by areeburrub** [comment]
I saw PR:#16,
I have added the blur navbar effect also.
Github page sample : https://areeburrub.github.io/Personal-Portfolio/

**Comment by Rishit30G** [comment]
Have you made the changes? 
@areeburrub

**Comment by areeburrub** [comment]
I have added the blur to the footer also, you can check it : https://areeburrub.github.io/Personal-Portfolio/

**Comment by areeburrub** [comment]
> image
> 
> Please check again! You have done great work, just make the same thing in the footer and you are good to go Ill add the label and merge it

Will I have to check and add the progress bar again to the project ?

**Comment by areeburrub** [comment]
Okay, sure
fixing the issues you mentioned. ✌️ 
Thanks 😄

**Pull request merged**
