### PR TITLE
Skill icons hover effect: Color change

### PR DESCRIPTION
**Pull request by Sriram-bb63**
Solves issue: #32

### CODE REVIEW

**Comment by Rishit30G** [comment]
Host the website online, so that I can see the changes clearly 👍🏻

**Comment by Sriram-bb63** [comment]
I have hosted the site here for demo purpose:
https://demo-pr-rishit30g.000webhostapp.com/

**Comment by Rishit30G** [comment]
image
image
image

Same goes for Flutter and C++ Icons 
They are quite dark on the background, if you could only find a way to make them better, 
I hope you take a look at the 2nd point of the above comment properly, you will make great progress then ✌

**Comment by Sriram-bb63** [comment]
Uhhh...wait I dont think the site is updated yet. It should have refreshed and updated by now. I will check it once if there is any problem.

**Pull request merged**
